server:
  port: 8080

spring:
  autoconfigure:
    exclude:
      - org.springframework.cloud.aws.autoconfigure.context.ContextInstanceDataAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextStackAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextRegionProviderAutoConfiguration
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://aws-case-itau.ci9lejzw9rq3.us-east-2.rds.amazonaws.com:5432/cat?currentSchema=domain
    platform: postgres
    initialization-mode: always
    continue-on-error: true
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

info:
  app:
    name: 'Itau Case Application'

url-cpf-integration: "https://user-info.herokuapp.com/users"

#timer-scheduled: 86400000
timer-scheduled: 120000

cloud:
  aws:
    region:
      static: us-east-2
      auto: false
    credentials:
      access-key: AKIATJTPJCPOEFQXJRHS
      secret-key: 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
    end-point:
      uri-queue-request: https://sqs.us-east-2.amazonaws.com/226792903644/nao-processada
      uri-queue-response: https://sqs.us-east-2.amazonaws.com/226792903644/queue-response

cat-api-url: https://api.thecatapi.com/v1

x-api-key: 80628546-a60b-419c-8e8a-c4bb2532842a
